 let dataDizi=[
    {
        id: Math.random(),
        title:"Bahar",
        image:"https://mo.ciner.com.tr/showtv/iu/393x220/bahar.jpg?v=1708289399",
        year: 2024,
        rate:6.3,
        decr:"عندما تواجه بهار الموت، ستكتشف وجهًا آخر لعائلتها التي تبدو (مثالية ) من الخارج، خاصة زوجها تيمور. مع مرض بهار المفاجئ، ستتغير جميع الديناميات في العائلة. خلال هذه العملية، سيكون إفرين منافسًا لتيمور في كل شيء. وجهود بهار لإعادة بناء حياتها ستجلب في كثير من الأحيان قصصًا تراجيديّة مضحكة تمنح المشاهدين الأمل",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%a8%d9%87%d8%a7%d8%b1/",
        lang:"Turkish",
        genre:"Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Senden once",
        image:"https://th.bing.com/th/id/OIF.plPBBqFkWNW3EmSdxdBtEg?rs=1&pid=ImgDetMain",
        year:2024,
        rate:5.4,
        decr:"هاكان داغستان صاحب أهم شركات البناء في البلاد ، يعيش مشاكل مع زوجته مروة تدخل حياته صحراء ، تختبر حبهما و وفاءهما تسعى مروة لتنظيف ما لطخته الصداقة في الماضي بواسطة الحب",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d9%85%d8%a7-%d9%82%d8%a8%d9%84%d9%83/",
        lang:"Turkish",
        genre:"Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"InciTaneleri",
        image:"https://th.bing.com/th/id/OIP._tDDn0Ie-7OF5VYVWBMSGwHaEK?rs=1&pid=ImgDetMain",
        year:2024,
        rate:6.3,
        decr:"بعد قضاء سنوات في السجن ، هل يعثر عازم على ما فقده ؟ عازم يسعى وراء الأمل محملاً بعبء على كتفيه و ماضياً مليئاً بالألم و بداخله سر كبير هل سيتمكن من اعادة تجميع حبات اللؤلؤ المتناثرة و المنفصلة من قلادته ؟ ",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%ad%d8%a8%d8%a7%d8%aa-%d8%a7%d9%84%d9%84%d8%a4%d9%84%d8%a4/",
        lang:"Turkish",
        genre:"Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"KOPUK",
        image:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/u0FEvBr9kLMmfyYju2Yro0XToXa.jpg",
        year:2024,
        rate:7.0,
        decr:"فرحان يسرق من الأثرياء ليساعد الفقراء في حيه، ولكن موت غير متوقع يقلب حياته. يقرر مواجهة التحديات باعتماد هوية جديدة (أورهان)، ويتورط في صدامات مع عائلة موجده الذي يحبها ومع وريثة عائلة تسعى للسيطرة على الحي. القصة تستكشف مواضيع العدالة والحب",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%a7%d9%84%d9%85%d8%aa%d8%b4%d8%b1%d8%af/",
        lang:"Turkish",
        genre:"Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"GADDAR",
        image:"https://th.bing.com/th/id/OIF.PlUF9bhozL3wKZyDSwEu9g?rs=1&pid=ImgDetMain",
        year:2024,
        rate:7.5,
        decr:"عند عودته إلى منزله بعد إنهاء خدمته العسكرية الطويلة، لم يعد عالم داغان كما تركه وقد أنقلبت حياته رأسًا على عقب.",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%a7%d9%84%d8%ba%d8%af%d8%a7%d8%b1/",
        lang:"Turkish",
        genre:"Actin Policier Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"KIZIL GONCALAR",
        image:"https://th.bing.com/th/id/OIP.sJYh_DgaDDxefo74fsbHqQHaDX?rs=1&pid=ImgDetMain",
        year:2024,
        rate:7.8,
        decr:"تدور قصة المسلسل حول التقاء مصير ليفانت الطبيب النفسي العلماني الذي يؤمن بمبادئ أتاتورك و مريم التي تعيش في بيئة محافظة",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%a7%d9%84%d8%a8%d8%b1%d8%a7%d8%b9%d9%85-%d8%a7%d9%84%d8%ad%d9%85%d8%b1%d8%a7%d8%a1/",
        lang:"Turkish",
        genre:"Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"ATES KUSLARI",
        image:"https://th.bing.com/th/id/OIP.DVdD-Z-26NcvF7f4ThclkgHaEK?w=711&h=400&rs=1&pid=ImgDetMain",
        year:2023,
        rate:6.2,
        decr:"مصير أطفال الشوارع إما السجن أو القبر. لكن هؤلاء الأطفال الخمسة الذين يطلقون على أنفسهم اسم بلا جذور تمكنوا من مقاومة هذا المصير. . فما هي قصتهم؟",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%b7%d9%8a%d9%88%d8%b1-%d8%a7%d9%84%d9%86%d8%a7%d8%b1/",
        lang:"Turkish",
        genre:"Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"SAFIR",
        image:"https://th.bing.com/th/id/OIP.A46GtrDDFp-qKRqoydpFwwHaEK?rs=1&pid=ImgDetMain",
        year:2023,
        rate:5.6,
        decr:"تجتمع عائلة من عائلات كابادوكيا البازة بعد عودة ابنهم الكبير من أمريكا. يقرر يامان أن يفاجئ حب طفولته فيرايا في عيد ميلادها بعرض الزواج عليها، لكن في تلك الليلة يحدث حادث مأساوي مع أخيه الصغير أوكان ما سيغير كل الأوضاع و يقلب حياة الجميع رأساً على عقب" ,
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%a7%d9%84%d9%8a%d8%a7%d9%82%d9%88%d8%aa/",
        lang:"Turkish",
        genre:"Drame Romantique",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Sahane Hayatim",
        image:"https://th.bing.com/th/id/OIP.hGOZNwCaMMFAGP8vuX80YAAAAA?rs=1&pid=ImgDetMain",
        year:2023,
        rate:5.5,
        decr:"قصة شبنم، الذي عاشت حياتها مع الظلم وعملت بجد للتغلب عليه، وقامت بما يلزم للنجاح في هذا الطريق، والآن تحاول الهروب من ماضيها المليء بالجرائم بينما تعيش حياة رائعة",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%ad%d9%8a%d8%a7%d8%aa%d9%8a-%d8%a7%d9%84%d8%b1%d8%a7%d8%a6%d8%b9%d8%a9/",
        lang:"Turkish",
        genre:"Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Sakla Beni",
        image:"https://th.bing.com/th/id/OIP.MayOBWafMVY7UtbVRQ4SqwHaEK?w=1280&h=720&rs=1&pid=ImgDetMain",
        year:2023,
        rate:4.8,
        decr:"ميته وناز أبناء عائلات غنية وقوية، تربيا في ترف وتدليل. إينجيلا، خادمة ناز منذ الطفولة، تظهر أمام ميته مما يجعله يتساءل عن قراراته السابقة. هل يؤدي هذا اللقاء إلى تغيير قصتهما وإلى إمكانية عثور ميته على حبه الحقيقي؟",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%ae%d8%a8%d8%a6%d9%86%d9%8a/",
        lang:"Turkish",
        genre:"Drame Famille Romantique",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Kirli Sepeti",
        image:"https://img.aydinlik.com.tr/rcman/Cw1280h720q95gc/storage/files/images/2023/09/29/kirli-sepeti-oyunculari-kim-konusu-ne-kirli-sepeti-1-bolum-full-izle-z2ie.jpg",
        year:2023,
        rate:5.7,
        decr:"بإحدى أحياء إسطنبول الثرية، يستعرض المسلسل قصة حياة الخادمات و أرباب عملهم في مجمع صغير، حيث نشاهد الفجوة الكبيرة بين الأغنياء و الفقراء. تدور الأحداث حول رحلة ثلاث نساء قررن مواجهة هذه التحديات معاً.",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%a7%d9%84%d8%b3%d9%84%d8%a9-%d8%a7%d9%84%d9%85%d8%aa%d8%b3%d8%ae%d8%a9/",
        lang:"Turkish",
        genre:"Comédie Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"HUDUTSUZ sevda",
        image:"https://www.yalovahayat.com/static/hu/hudutsuz-sevda-hangi-gun-1695299762-913.jpeg",
        year:2023,
        rate:6.9,
        decr:"عندما كان طفلاً صغيراً، فقد خليل إبراهيم والده بسبب نزاع دموي وتم نفيه إلى اسطنبول. بعد مرور عشرين عامًا، عاد خليل إبراهيم إلى بلاده في منطقة البحر الأسود. هناك، كان ينوي الزواج من الفتاة التي يحبها ياسمين وبناء حياة جديدة. ولكن الأحداث لم تسمح له بذلك. حياته ستتغير تمامًا عندما تظهر زينب من عائلة ليتو في حياته، حيث يخوض خليل إبراهيم رحلة انتقامية.",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%ad%d8%a8-%d8%a8%d9%84%d8%a7-%d8%ad%d8%af%d9%88%d8%af/",
        lang:"Turkish",
        genre:"Action Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"YABANI",
        image:"https://www.passioneturchia.it/wp-content/uploads/2023/09/img_5905-1024x576.jpg",
        year:2023,
        rate:7.3,
        decr:"القصة تروي معاناة طفل تم اختطافه من عائلة ذات جذور عميقة وسقوطه في الشوارع، ثم محاولته للعودة إلى منزله بعد مرور سنوات و صراعه في إعادة بناء حياته",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%a7%d9%84%d9%85%d8%aa%d9%88%d8%ad%d8%b4/",
        lang:"Turkish",
        genre:"Drame Romantique",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"KARDESLERIM",
        image:"https://iaatv.tmgrup.com.tr/893c78/0/0/0/0/0/0?u=https://iatv.tmgrup.com.tr/2021/06/10/500x268/1623318076432.jpg",
        year:2021,
        rate:5.9,
        decr:"أربعة أخوة يعيشون حياة سعيدة مع والديهم، فقراء بجيوب فارغة لكن قلوبهم مليئة بالحب. تنقلب حياتهم في يوم أسود أظلم حياتهم وتركهم وحيدين بدون والديهم.",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%a3%d8%ae%d9%88%d8%aa%d9%8a/",
        lang:"Turkish",
        genre:"Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Yali çapkini",
        image:"https://www.elaosboa.com/wp-content/uploads/2022/12/elaosboa69130.jpg",
        year:2022,
        rate:6.1,
        decr:"لتلقين حفيده الطائش والمتهور درسا، يقرر الجد الغني أن يزوج حفيده بإبنة عائلة من مسقط رأسه!",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%a7%d9%84%d8%b7%d8%a7%d8%a6%d8%b1-%d8%a7%d9%84%d8%b1%d9%81%d8%b1%d8%a7%d9%81/",
        lang:"Turkish",
        genre:"Drame Romantique",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Kizilcik Sirabeti",
        image:"https://mo.ciner.com.tr/showtv/iu/393x220/kizilcik-serbeti.jpg?v=1708334605",
        year:2022,
        rate:6.6,
        decr:"تدور القصة حول الأحداث المدهشة التي أعقبت زواج دوغا وفاتح، وهما من عائلتين من ثقافات مختلفة كلياً!",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%b4%d8%b1%d8%a7%d8%a8-%d8%a7%d9%84%d8%aa%d9%88%d8%aa/",
        lang:"Turkish",
        genre:"Drame Romantique",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"YARGI",
        image:"https://canlitv.com/resimler/blog/yurdaer-okur-yargi-dizisine-basmufettis-olarak-dahil-oldu.jpg",
        year:2021,
        rate:8.3,
        decr:"يجب على الغاز وجيلين العمل معًا للعثور على المجرم في قضية قتل. لكن هذا سيخلق نقطة انهيار لا رجعة فيها في حياة كل منهما!",
        stream:"https://eshaaq.com/series/%d8%a7%d9%84%d9%82%d8%b6%d8%a7%d8%a1-%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d9%82%d8%b5%d8%a9-%d8%b9%d8%b4%d9%82/",
        lang:"Turkish",
        genre:"Policier Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Kendi dusen aglamz",
        image:"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhMSRF3zqI7Dly-nKbxtfSo6zzPbNrKqLRJut2i0OxA3HUFHudWGfDRetCYFUNal2jX1h1zQMiwRvRfHIerZIeLcXi7B7LuJkSovboThiXMwRbstfls7EEmx0ZXyg9OY92CLtn8l8TLDZo1yQXAXNbe75fiJP9yp8HAWk6oq4PDTCJxapFrkjRtJNbNm6E/s1200/Kendi-Dusen-Aglamaz-Su-Saida-No-Llora-Capitulo-2-Novela-Turca.jpg",
        year:2023,
        rate:6.4,
        decr:"أليزا تحاول منع والدها الذي يفكر في الزواج مرة أخرى بعد وفاة والدتها",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d9%85%d9%86-%d9%8a%d9%82%d8%b9-%d8%a8%d9%86%d9%81%d8%b3%d9%87-%d9%84%d8%a7-%d9%8a%d8%a8%d9%83%d9%8a/",
        lang:"Turkish",
        genre:"Comedie Drame Famille",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Bir Derdim var",
        image:"https://img.dizi.la/uploads/76910/bir-derdim-var.jpg",
        year:2023,
        rate:7.1,
        decr:"الدكتورة نيلوفر توسكا، متخصصة في علاج المشاكل النفسية للمراهقين، تمتلك حدة ذكاء وقدرة على حل مشاكل تبدو مستحيلة. لكنها تخفي سرًا كبيرًا وتجد نفسها في صراع مع المدعي العام عمر وعندما تجد الحب في حياتها، تجد نفسها مضطرة لمواجهة هذا السر والجنون الذي يحمله الحب.",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d9%84%d8%af%d9%8a-%d9%87%d9%85/",
        lang:"Turkish",
        genre:"Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"AILE",
        image:"https://safirakademimenajerlik.com/wp-content/uploads/2023/03/1200x627-aile-dizisi-basliyor-aile-dizisi-konusu-oyunculari-ve-cekildigi-yer-bilgisi-1678109432580.jpg",
        year:2023,
        rate:6.5,
        decr:"هل من الممكن لشخص آخر أن يملأ الفراغ الذي تسببه العائلة؟",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%a7%d9%84%d8%b9%d8%a7%d8%a6%d9%84%d8%a9/",
        lang:"Turkish",
        genre:"Action Drame Policier",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Teskilet",
        image:"https://img.internethaber.com/rcman/Cw1152h720q95gc/storage/files/images/2022/08/12/teskilatkpk-Wb3S_cover.jpg",
        year:2021,
        rate:6.6,
        decr:"ينفذ هجوم ارهابي في مصنع للطائرات في أنقرة. بعد هذا الهجوم، يتم تأسيس فريق سري للغاية في منظمة الاستخبارات الوطنية. سيتخلى أعضاء هذا الفريق عن حياتهم من أجل بلدهم في محاولة لتحديد الجهة المسؤولة عن هذه الهجمات.",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%a7%d9%84%d9%85%d9%86%d8%b8%d9%85%d8%a9/",
        lang:"Turkish",
        genre:"Action Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Adim FARAH",
        image:"https://www.passioneturchia.it/wp-content/uploads/2023/03/img_7094-1024x580.jpg",
        year:2023,
        rate:6.4,
        decr:"فرح والتي اضطرت إلى الفرار من بلدها وتكافح بشكل غير قانوني للبقاء على قيد الحياة مع ابنها، تشهد جريمة قتل عن غير قصد. لكن ما سيغيّر حياتها الى الأبد هو لقاءها بطاهر في نفس الليلة!",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%a7%d8%b3%d9%85%d9%8a-%d9%81%d8%b1%d8%ad/",
        lang:"Turkish",
        genre:"Action Drame Policier",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Uc Kizkardes",
        image:"https://khaleej-trend.online/wp-content/uploads/2022/02/%D9%85%D8%B3%D9%84%D8%B3%D9%84-%D8%AB%D9%84%D8%A7%D8%AB-%D8%A7%D8%AE%D9%88%D8%A7%D8%AA-%D9%85%D8%AA%D8%B1%D8%AC%D9%85.jpg",
        year:2022,
        rate:4.4,
        decr:"بينما تعيش الأخوات الثلاثة حياةً سعيدة مع والديهن، تبدأ الغيوم السوداء بالحوم فوق العائلة حين تتزوج الأخت الكبرى تاركان. وفي الوقت الذي تحاول فيه تاركان إخفاء تعاستها بسبب هذا الزواج، تنقلب حياة الأخت الأخرى دوندان رأساً على عقب حين يظهر سر كبير من الماضي. أمّا الأخت الثالثة فهي على وشك إتخاذ قرار لا رجعة فيه. هل سيتمكن الأب والأم من انقاذ الأخوات الثلاثة من حافة الهاوية؟",
        stream:"https://eshaaq.com/series/%d8%ab%d9%84%d8%a7%d8%ab-%d8%a3%d8%ae%d9%88%d8%a7%d8%aa-%d9%85%d8%aa%d8%b1%d8%ac%d9%85/",
        lang:"Turkish",
        genre:"Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Dilek Tasi",
        image:"https://th.bing.com/th/id/OIP.NvKJ8SaZFq7KHHcH27yp0AAAAA?rs=1&pid=ImgDetMain",
        year:2023,
        rate:5.7,
        decr:"مصطفى يواجه تحديًا كبيرًا؛ حيث يحتاج إلى مبلغ كبير لعملية جراحية ضرورية لزوجته المريضة بمرض خطير. الشركة التي كان يعمل فيها مغلقة، وهو يبحث عن أي طريقة للحصول على الأموال، فقرر مطالبة صاحب المصنع بالرواتب المتأخرة لشهور لإجراء العملية. هذا القرار سيغير حياة مصطفى وابنته جيمري",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%ad%d8%ac%d8%b1-%d8%a7%d9%84%d8%a3%d9%85%d9%86%d9%8a%d8%a7%d8%aa/",
        lang:"Turkish",
        genre:"Drame Historique",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Ya Cok Seversen",
        image:"https://icdn.ensonhaber.com/resize/1200x675-85/resimler/diger/kok/2023/06/23/kanal-dnin-yeni-dizisi-icin-heyecan-dorukta-ya-cok-seversen-1-bolum_561e9564.jpg",
        year:2023,
        rate:7.1,
        decr:"أتاش الذي قضى حياته خارج البلاد ، بعد وفاة والده يضطر للعودة الى اسطنبول التي تركها منذ سنوات ، و هو يبحث عن عائلته يلتقي بليلى ",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d9%85%d8%a7%d8%b0%d8%a7-%d9%84%d9%88-%d8%a3%d8%ad%d8%a8%d8%a8%d8%aa-%d9%83%d8%ab%d9%8a%d8%b1%d8%a7%d9%8b/",
        lang:"Turkish",
        genre:"Comédie Drame Romantique",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Yildizlar Bana Uzak",
        image:"https://hursozgazetesicom.teimg.com/crop/1280x720/hursozgazetesi-com/uploads/2023/12/yildizlar-bana-uyarlama-mi.jpg",
        year:2023,
        rate:7.2,
        decr:"آصلي و قادر اللذان يحبان بعضهما لسنوات ، يقرران الزواج لكن هذا القرار يعتبر خبراً سيئاً لآخرين هل سينجح هان في تحقيق خطته لمنع هذا الزواج ؟ كيف ستتغير حياة أصلي وقادر معًا في ظل التحديات القادمة ؟",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%a7%d9%84%d9%86%d8%ac%d9%88%d9%85-%d8%a8%d8%b9%d9%8a%d8%af%d8%a9-%d8%b9%d9%86%d9%8a/",
        lang:"Turkish",
        genre:"Action Drame Romantique",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Kader Baglari",
        image:"https://turcas9.com/wp-content/uploads/kader-baglari-espanol.jpg",
        year:2023,
        rate:4.6,
        decr:"قصة حب شغوفة ومجنونة بين شابين التقيا في كروم العنب حيث تتقاطع طرقهما ، تروي قصة حب وصراع سيفدا و كرم ، شخصان من عالمين مختلفين",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%b1%d9%88%d8%a7%d8%a8%d8%b7-%d8%a7%d9%84%d9%82%d8%af%d8%b1/",
        lang:"Turkish",
        genre:"Drame Romantique",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"ASKA Dusman",
        image:"https://img3.aksam.com.tr/imgsdisk/2024/01/04/t25_aska-dusman-konusu-nedir--205.jpg",
        year:2024,
        rate:4.2,
        decr:"هنالك من يحلف بالحب و هنالك من يحلف ليكون ضده",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%b9%d8%af%d9%88-%d8%a7%d9%84%d8%ad%d8%a8/",
        lang:"Turkish",
        genre:"Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Donence",
        image:"https://turkishdramaworld.com/wp-content/uploads/2023/07/Donence-800x445.jpg",
        year:2023,
        rate:5.2,
        decr:"",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%a7%d9%84%d9%85%d8%af%d8%a7%d8%b1/",
        lang:"Turkish",
        genre:"Drame Romantique",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Ruhun Duymaz",
        image:"https://saraydorf.de/dizi/dizi/image/ruhun-duymaz.jpg",
        year:2023,
        rate:7.0,
        decr:"",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%af%d9%88%d9%86-%d8%a3%d9%86-%d8%aa%d8%b4%d8%b9%d8%b1/",
        lang:"Turkish",
        genre:"Comédie Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Gulcemal",
        image:"https://www.febspot.com/contents/videos_screenshots/1154000/1154798/preview_720p.mp4.jpg",
        year:2023,
        rate:7.2,
        decr:"يتحدث المسلسل عن قصة حب بين جول جمال الذي تحول إلى وحش مظلم بسبب ترك والدته له، وديفا الجميلة. تبدأ علاقتهما بالكراهية وتتطور لتصبح شغفًا وعاصفة عاطفية. تتعرض علاقتهما للتحديات بين الحب غير المتوقع والحقد الذي حمله جول جمال لسنوات. تتساءل القصة عما إذا كان جول جمال سيتحول من صياد قاسٍ إلى فريسة، وهل ستدرك ديفا أن هذا الحب مستحيل عندما تستسلم أخيرًا.",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%ac%d9%88%d9%84-%d8%ac%d9%85%d8%a7%d9%84/",
        lang:"Turkish",
        genre:"Romantique Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Veda Mektubu",
        image:"https://canlitv.com/resimler/blog/veda-mektubu-dizisi-bu-aksam-basliyor.jpg",
        year:2023,
        rate:6.2,
        decr:"ما لم نستطع أن نعيشه، ما لم نتمكن من التعبير عنه، ما كنا نخاف منه، أولئك الذين هربنا منهم، أولئك الذين لم نجرؤ على أن نكون معهم، كل هذا سيدخل حياتنا عن طريق أطفالنا ليكون أكبر اختبار لنا. فهل أنت مستعد لهذا الإختبار؟",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%b1%d8%b3%d8%a7%d9%84%d8%a9-%d9%88%d8%af%d8%a7%d8%b9/",
        lang:"Turkish",
        genre:"Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Yaz Sarkisi",
        image:"https://tr.web.img2.acsta.net/pictures/23/06/27/12/13/2392218.jpg",
        year:2023,
        rate:5.3,
        decr:"تدور أحداث المسلسل حول ياز التي تأتي الى إسطنبول من أجل اكمال دراستها تحاول تحقيق حلم والدها خفية عن أمها",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%a3%d8%ba%d9%86%d9%8a%d8%a9-%d8%a7%d9%84%d8%b5%d9%8a%d9%81/",
        lang:"Turkish",
        genre:"Drame Musical Comédie",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Taçsiz prenses",
        image:"https://static.next-episode.net/tv-shows-images/huge/tacsiz-prenses.jpg",
        year:2023,
        rate:6.8,
        decr:"مسال والتي كبرت وهي تسمع الحكايات الخرافية من والدتها الحالمة شيرين، تنصدم بالواقع المرير حين تدخل والدتها المستشفى بسبب مرض في القلب.",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%a3%d9%85%d9%8a%d8%b1%d8%a9-%d8%a8%d9%84%d8%a7-%d8%aa%d8%a7%d8%ac/",
        lang:"Turkish",
        genre:"Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Uvey Anne",
        image:"https://www.natabanu.com/images/2023/maceha.jpg",
        year:2023,
        rate:4.4,
        decr:"يحكي المسلسل قصة سراب التي تحاول الحصول على قلب فاروق والد لثلاثة أطفال بعد وفاة زوجته",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%b2%d9%88%d8%ac%d8%a9-%d8%a7%d9%84%d8%a3%d8%a8/",
        lang:"Turkish",
        genre:"Drame",
        Add:"https://eshaaq.com/login",
    },
    {
        id: Math.random(),
        title:"Ne Gemiler Yaktim",
        image:"https://iasbh.tmgrup.com.tr/c51b8b/400/211/0/0/1920/1014?u=https://isbh.tmgrup.com.tr/sb/album/2023/12/04/ne-gemiler-yaktim-oyunculari-ve-konusu-show-tvnin-yeni-dizisi-ne-gemiler-yaktim-konusu-nedir-oyunculari-kimler-1701711504282.jpg",
        year:2023,
        rate:6.4,
        decr:"يحكي المسلسل قصة التقاء ياسمين و فيدان ، اللتين ليس لديهما أي تشابه سوى الأمومة يروي قصة رحلتهما في البقاء على قيد الحياة و التضامن ، المفتش توبراك يتدخل لكشف أفعال روكتاي ، الزوج الذي تركته فيدان خلفها سيكون لهم تأثير كبير على حياة ياسمين و فيدان",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d9%83%d9%85-%d9%85%d9%86-%d8%a7%d9%84%d8%b3%d9%81%d9%86-%d8%a3%d8%ad%d8%b1%d9%82%d8%aa/",
        lang:"Turkish",
        genre:"Drame",
        Add:"",
    },
    {
        id: Math.random(),
        title:"Sandik Kokusu",
        image:"https://th.bing.com/th/id/R.0d2470b3cb991bffa654ef495a2ed749?rik=IV4HDwHV0qW9aA&riu=http%3a%2f%2fsaraydorf.de%2fdizi%2fdizi%2fimage%2fsandik-kokusu.jpg&ehk=iMtu%2b7TJ%2fGNvknNwQ0M8G%2bash4Tniz5O1GV4QOA83FY%3d&risl=&pid=ImgRaw&r=0",
        year:2023,
        rate:6.3,
        decr:"كارسو أنجبت مؤخرًا طفلها الثالث، وحضرت والدتها فيليز للمساعدة. لتخفيف الضغط عن ابنتها، قررت فيليز أن تأخذ ابن كارسو، كوزاي، إلى اسطنبول. يحدث حادث مؤسف أثناء رحيلهم، يؤدي إلى فقدان كوزاي. تنهار حياة كارسو بسبب هذا الحادث، وفي النهاية، تنفصل كارسو وفيليز عن بعضهما البعض دون أن يلتقيا مرة أخرى",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%b1%d8%a7%d8%a6%d8%ad%d8%a9-%d8%a7%d9%84%d8%b5%d9%86%d8%af%d9%88%d9%82/",
        lang:"Turkish",
        genre:"Drame",
        Add:"",
    },
    {
        id: Math.random(),
        title:"KARA",
        image:"https://tr.web.img2.acsta.net/pictures/23/12/28/12/14/4454492.jpg",
        year:2023,
        rate:4.0,
        decr:"سيشعر كارا وزينب وكأنهما يعرفان بعضهما البعض حتى قبل أن يلتقيا، فرغم أنهما يعيشان حياة مختلفة تمامًا، تقاطعت طرقهما في الماضي. يسعى كارا لفهم الحقيقة وراء سقوط والده ظلمًا في السجون، كل منهما يواجه الجرح الذي يحرق قلبه. فهل سيقرب هذا الجرح بينهما، أم سيبعدهما عن بعضهما؟",
        stream:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d9%83%d8%a7%d8%b1%d8%a7/",
        lang:"Turkish",
        genre:"Drame",
        Add:"",
    },
    {
        id: Math.random(),
        title:"AVLU",
        image:"https://1001dizi.net/images2/dizi/arsiv/avlu.jpg",
        year:2018,
        rate:7.2,
        decr:"يحكي المسلسل قصص وصراعات السجينات، ويلقي الضوء على الفوضى والفساد المنتشر داخل السجن.",
        strem:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%a7%d9%84%d9%81%d9%86%d8%a7%d8%a1/",
        lang:"Turkish",
        genre:"Policier Drame",
        Add:"",
    },
    {
        id: Math.random(),
        title:"Ufak Tefek Cinayetlar",
        image:"https://i.ytimg.com/vi/yWCR76CFCTA/maxresdefault.jpg",
        year:2017,
        rate:7.3,
        decr:" يلتم شمل الصديقات الأربعة بعد عودة أويا إلى البلدة التي كانت تعيش فيها قبل انتقالها إلى منطقة أخرى للدراسة. لكن الماضي الذي فرق بينهن في يوم من الأيام يعود من جديد!يحكي المسلسل قصص وصراعات السجينات، ويلقي الضوء على الفوضى والفساد المنتشر داخل السجن.",
        strem:"https://eshaaq.com/series/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%ac%d8%b1%d8%a7%d8%a6%d9%85-%d8%b5%d8%ba%d9%8a%d8%b1%d8%a9/",
        lang:"Turkish",
        genre:"Action Policier Drame",
        Add:"",
    },
];

export default dataDizi